models/Surat.php
<?php

namespace app\models;

use Yii;
use app\components\Helper;

/**
 * This is the model class for table "surat".
 *
 * @property integer $id
 * @property integer $id_surat_kop
 * @property integer $id_surat_jenis
 * @property integer $id_surat_sifat
 * @property integer $id_surat_status
 * @property integer $id_surat_metode
 * @property integer $id_jabatan_penandatangan
 * @property integer $id_jabatan_penerbit
 * @property string $username_pengaju
 * @property string $username_pembuat
 * @property string $username_penerbit
 * @property string $username_penandatangan
 * @property string $nomor
 * @property integer $urutan
 * @property string $tanggal
 * @property string $ringkasan
 * @property string $draf
 * @property string $berkas
 * @property string $lampiran
 * @property string $tujuan
 * @property string $tujuan_jabatan
 * @property string $tujuan_pegawai
 * @property string $tembusan
 * @property string $tembusan_jabatan
 * @property string $tembusan_laporan
 * @property string $tembusan_pegawai
 * @property string $waktu_dibuat
 * @property string $waktu_diajukan
 * @property string $waktu_disetujui
 * @property string $waktu_diterbitkan
 *
 * @property Distribusi[] $distribusis
 * @property Paraf[] $parafs
 * @property Jabatan $idJabatanPengaju
 * @property SuratJenis $idSuratJenis
 * @property SuratSifat $idSuratSifat
 * @property SuratStatus $idSuratStatus
 * @property SuratKop $idSuratKop
 * @property SuratMetode $idSuratMetode
 * @property Jabatan $idJabatanPenandatangan
 * @property Jabatan $idJabatanPenerbit
 * @property Jabatan $idJabatanPembuat
 * @property SuratAtribut[] $suratAtributs
 */
class Surat extends \yii\db\ActiveRecord
{
    public $paraf;

    const EVENT_AFTER_CREATE_DRAFT = 'after_create_draft';

    public function init()
    {
        $this->on(self::EVENT_AFTER_CREATE_DRAFT, [$this, 'setTanggal']);
        $this->on(self::EVENT_AFTER_CREATE_DRAFT, [$this, 'setNomor']);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'surat';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_surat_jenis', 'id_surat_sifat', 'id_jabatan_penandatangan', 'ringkasan', 'paraf'], 'required'],
            [['paraf','id_surat_kop', 'id_surat_jenis', 'id_surat_sifat', 'id_surat_status', 'id_surat_metode', 'id_jabatan_penandatangan', 'id_jabatan_penerbit', 'urutan'], 'integer'],
            [['tanggal', 'waktu_dibuat', 'waktu_diajukan', 'waktu_disetujui', 'waktu_diterbitkan'], 'safe'],
            [['ringkasan', 'tujuan', 'tujuan_jabatan', 'tujuan_pegawai', 'tembusan', 'tembusan_jabatan', 'tembusan_laporan', 'tembusan_pegawai'], 'string'],
            [['username_pengaju', 'username_pembuat', 'username_penerbit', 'username_penandatangan', 'nomor', 'draf', 'berkas', 'lampiran'], 'string', 'max' => 255],

            [['id_jabatan_penandatangan'], 'exist', 'skipOnError' => true, 'targetClass' => Jabatan::className(), 'targetAttribute' => ['id_jabatan_penandatangan' => 'id']],
            [['id_jabatan_penerbit'], 'exist', 'skipOnError' => true, 'targetClass' => Jabatan::className(), 'targetAttribute' => ['id_jabatan_penerbit' => 'id']],

            [['username_pengaju'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['username_pengaju' => 'username']],
            [['username_penandatangan'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['username_penandatangan' => 'username']],
            [['username_penerbit'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['username_penerbit' => 'username']],
            [['username_pembuat'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['username_pembuat' => 'username']],

            [['id_surat_jenis'], 'exist', 'skipOnError' => true, 'targetClass' => SuratJenis::className(), 'targetAttribute' => ['id_surat_jenis' => 'id']],
            [['id_surat_sifat'], 'exist', 'skipOnError' => true, 'targetClass' => SuratSifat::className(), 'targetAttribute' => ['id_surat_sifat' => 'id']],
            [['id_surat_status'], 'exist', 'skipOnError' => true, 'targetClass' => SuratStatus::className(), 'targetAttribute' => ['id_surat_status' => 'id']],
            [['id_surat_kop'], 'exist', 'skipOnError' => true, 'targetClass' => SuratKop::className(), 'targetAttribute' => ['id_surat_kop' => 'id']],
            [['id_surat_metode'], 'exist', 'skipOnError' => true, 'targetClass' => SuratMetode::className(), 'targetAttribute' => ['id_surat_metode' => 'id']],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_surat_kop' => 'Kop Surat',
            'id_surat_jenis' => 'Jenis Surat',
            'id_surat_sifat' => 'Sifat Surat',
            'id_surat_status' => 'Status Surat',
            'id_surat_metode' => 'Metode Surat',
            'id_jabatan_penandatangan' => 'Jabatan Penandatangan',
            'id_jabatan_penerbit' => 'Jabatan Penerbit',
            'username_pengaju' => 'Username Pengaju',
            'username_pembuat' => 'Username Pembuat',
            'username_penerbit' => 'Username Penerbit',
            'username_penandatangan' => 'Username Penandatangan',
            'nomor' => 'Nomor',
            'urutan' => 'Urutan',
            'tanggal' => 'Tanggal',
            'ringkasan' => 'Ringkasan',
            'draf' => 'Draf',
            'berkas' => 'Berkas',
            'lampiran' => 'Lampiran',
            'tujuan' => 'Tujuan',
            'tujuan_jabatan' => 'Tujuan Jabatan',
            'tujuan_pegawai' => 'Tujuan Pegawai',
            'tembusan' => 'Tembusan',
            'tembusan_jabatan' => 'Tembusan Jabatan',
            'tembusan_laporan' => 'Tembusan Laporan',
            'tembusan_pegawai' => 'Tembusan Pegawai',
            'waktu_dibuat' => 'Waktu Dibuat',
            'waktu_diajukan' => 'Waktu Diajukan',
            'waktu_disetujui' => 'Waktu Disetujui',
            'waktu_diterbitkan' => 'Waktu Diterbitkan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistribusis()
    {
        return $this->hasMany(Distribusi::className(), ['id_surat' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParafs()
    {
        return $this->hasMany(Paraf::className(), ['id_surat' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJabatanPenandatangan()
    {
        return $this->hasOne(Jabatan::className(), ['id' => 'id_jabatan_penandatangan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdJabatanPenerbit()
    {
        return $this->hasOne(Jabatan::className(), ['id' => 'id_jabatan_penerbit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserPengaju()
    {
        return $this->hasOne(User::className(), ['username' => 'username_pengaju']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserPembuat()
    {
        return $this->hasOne(User::className(), ['username' => 'username_pembuat']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPegawaiPengaju()
    {
        return $this->hasOne(Pegawai::className(), ['id' => 'id_pegawai'])
            ->via('userPengaju');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPegawaiPembuat()
    {
        return $this->hasOne(Pegawai::className(), ['id' => 'id_pegawai'])
            ->via('userPembuat');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJabatanPengaju()
    {
        return $this->hasOne(Jabatan::className(), ['id' => 'id_jabatan'])
            ->via('pegawaiPengaju');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJabatanPembuat()
    {
        return $this->hasOne(Jabatan::className(), ['id' => 'id_jabatan'])
            ->via('pegawaiPembuat');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserPenerbit()
    {
        return $this->hasOne(User::className(), ['username' => 'username_penerbit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserPenandatangan()
    {
        return $this->hasOne(User::className(), ['username' => 'username_penandatangan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratJenis()
    {
        return $this->hasOne(SuratJenis::className(), ['id' => 'id_surat_jenis']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratSifat()
    {
        return $this->hasOne(SuratSifat::className(), ['id' => 'id_surat_sifat']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratStatus()
    {
        return $this->hasOne(SuratStatus::className(), ['id' => 'id_surat_status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratKop()
    {
        return $this->hasOne(SuratKop::className(), ['id' => 'id_surat_kop']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdSuratMetode()
    {
        return $this->hasOne(SuratMetode::className(), ['id' => 'id_surat_metode']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratAtributs()
    {
        return $this->hasMany(SuratAtribut::className(), ['id_surat' => 'id']);
    }

    public function getListSuratKop()
    {
        return SuratKop::getList();
    }

    public function getListSuratJenis()
    {
        return SuratJenis::getList();
    }

    public function getListSuratSifat()
    {
        return SuratSifat::getList();
    }

    public function getListJabatanPendandatangan()
    {

controllers/SuratController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Surat;
use app\models\SuratSearch;
use app\models\SuratStatus;
use kartik\mpdf\Pdf;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SuratController implements the CRUD actions for Surat model.
 */
class SuratController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Surat models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SuratSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Surat model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Surat model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Surat();

        // Nanti ini dibuat dinamis berdasarkan yang login!
        $model->username_pembuat = '60010951';
        $model->id_surat_status = SuratStatus::KONSEP;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->trigger(Surat::EVENT_AFTER_CREATE_DRAFT);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Surat model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->id_surat_status = SuratStatus::KONSEP;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Surat model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Surat model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Surat the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Surat::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPdf($id)
    {
        $model = $this->findModel($id);

        $content = $this->renderPartial('_pdf',[
            'model' => $model,
        ]);

        $marginLeft = 10;
        $marginRight = 10;
        $marginTop = 10;
        $marginBottom = 20;
        $marginHeader = 5;
        $marginFooter = 5;

        $cssInline = <<<CSS
                thead {
                    display: table-header-group;
                }

                tfoot {
                    display: table-footer-group;
                }
                .padding td, .padding th {
                    padding : 10px;
                }

                .padding tr {
                    min-height: 80px;
                }

                tr, th {
                    padding:6px;
                }

                tr th.no-border-cell, tr td.no-border-cell {
                    border-width: 0px 0px 0px 1px;
                    border-style: solid;
                    border-color: black;
                }

                .no-border {
                    width: 100%;
                }

                .no-border th, .no-border td {
                    border:none;
                }

                .border {
                    width : 100%;
                    border-collapse : collapse;
                }

                .border th, .border td {
                    border : 1px solid black;
                    border-collapse : collapse;
                }

                .bold {
                    font-weight : bold;
                }

                .t-center {
                    text-align : center;
                }

                .v-center {
                    vertical-align: :center;
                }
CSS;

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_FOLIO,
            // portrait orientation
            'orientation' => Pdf::ORIENT_LANDSCAPE,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input

            'marginLeft' => $marginLeft,
            'marginRight' => $marginRight,
            'marginTop' => $marginTop,
            'marginBottom' => $marginBottom,
            'marginHeader' => $marginHeader,
            'marginFooter' => $marginFooter,

            'content' => $content,

            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => $cssInline,
             // set mPDF properties on the fly
            'options' => ['title' => 'RKA SKPD'],
             // call mPDF methods on the fly
            'methods' => []
        ]);

        return $pdf->render();
    }
}

views/surat/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Surat */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-primary surat-form">
    <div class="box-header with-border">
        <h3 class="box-title">Form surat</h3>
    </div>
    <div class="box-body">
    <?php $form = ActiveForm::begin([
                        'layout'=>'horizontal',
                        'fieldConfig' => [
                        'horizontalCssClasses' => [
                            'label' => 'col-sm-3',
                            'wrapper' => 'col-sm-4',
                            'error' => '',
                            'hint' => '',
                    ],
                    ]]); ?>

    <?= $form->field($model, 'id_surat_jenis')->widget(Select2::className(), [
        'data' => $model->getListSuratJenis(),
        'options' => [
            'placeholder' => '- Pilih Jenis -',
        ],
        'pluginOptions' => [
            'allowClear' => true,
        ]
    ]) ?>

    <?= $form->field($model, 'id_surat_sifat')->widget(Select2::className(), [
        'data' => $model->getListSuratSifat(),
        'options' => [
            'placeholder' => '- Pilih Sifat -',
        ],
        'pluginOptions' => [
            'allowClear' => true,
        ]
    ]) ?>

    <?= $form->field($model, 'id_jabatan_penandatangan')->widget(Select2::className(), [
        'data' => $model->getListJabatanPendandatangan(),
        'options' => [
            'placeholder' => '- Pilih Penandatangan -',
        ],
        'pluginOptions' => [
            'allowClear' => true,
        ]
    ]) ?>

    <?= $form->field($model, 'ringkasan')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'username_pengaju')->widget(Select2::className(), [
        'data' => $model->getListUserPegawai(),
        'options' => [
            'placeholder' => 'Sama dengan pembuat',
        ],
        'pluginOptions' => [
            'allowClear' => true,
        ]
    ]) ?>

    <?= $form->field($model, 'paraf')->widget(Select2::className(), [
        'data' => $model->getListParaf(),
    ]) ?>

    </div>
    <div class="box-footer with-border form-group">
        <div class="col-sm-3 col-sm-offset-3">
            <?= Html::submitButton('Simpan', ['class' => 'btn btn-success btn-flat']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/surat/_pdf.php
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias tempora earum perspiciatis eligendi ullam. At fugiat laudantium, aliquid quisquam ex illum ad reprehenderit alias harum laboriosam! Ipsam culpa distinctio illo voluptas vero quasi in laborum veniam, atque ipsum asperiores nihil temporibus saepe sit. Possimus a deleniti maxime exercitationem ratione quod, aliquid pariatur ducimus voluptate, ex odit inventore nihil sit numquam iusto dignissimos laudantium accusamus libero ullam, dolor itaque ad quis porro. Molestias et quasi aliquam eligendi, praesentium placeat illo provident, doloremque sapiente a sunt quas asperiores ipsa nesciunt, iste. Temporibus illum, recusandae perspiciatis ducimus numquam quos odit possimus distinctio omnis.

views/surat/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SuratSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="surat-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_surat_kop') ?>

    <?= $form->field($model, 'id_surat_jenis') ?>

    <?= $form->field($model, 'id_surat_sifat') ?>

    <?= $form->field($model, 'id_surat_status') ?>

    <?php // echo $form->field($model, 'id_surat_metode') ?>

    <?php // echo $form->field($model, 'id_jabatan_penandatangan') ?>

    <?php // echo $form->field($model, 'id_jabatan_penerbit') ?>

    <?php // echo $form->field($model, 'id_jabatan_pembuat') ?>

    <?php // echo $form->field($model, 'id_jabatan_pengaju') ?>

    <?php // echo $form->field($model, 'username_pengaju') ?>

    <?php // echo $form->field($model, 'username_pembuat') ?>

    <?php // echo $form->field($model, 'username_penerbit') ?>

    <?php // echo $form->field($model, 'username_penandatangan') ?>

    <?php // echo $form->field($model, 'nomor') ?>

    <?php // echo $form->field($model, 'urutan') ?>

    <?php // echo $form->field($model, 'tanggal') ?>

    <?php // echo $form->field($model, 'ringkasan') ?>

    <?php // echo $form->field($model, 'draf') ?>

    <?php // echo $form->field($model, 'berkas') ?>

    <?php // echo $form->field($model, 'lampiran') ?>

    <?php // echo $form->field($model, 'tujuan') ?>

    <?php // echo $form->field($model, 'tujuan_jabatan') ?>

    <?php // echo $form->field($model, 'tujuan_pegawai') ?>

    <?php // echo $form->field($model, 'tembusan') ?>

    <?php // echo $form->field($model, 'tembusan_jabatan') ?>

    <?php // echo $form->field($model, 'tembusan_laporan') ?>

    <?php // echo $form->field($model, 'tembusan_pegawai') ?>

    <?php // echo $form->field($model, 'waktu_dibuat') ?>

    <?php // echo $form->field($model, 'waktu_diajukan') ?>

    <?php // echo $form->field($model, 'waktu_disetujui') ?>

    <?php // echo $form->field($model, 'waktu_diterbitkan') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/surat/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Surat */

$this->title = 'Tambah Surat';
$this->params['breadcrumbs'][] = ['label' => 'Surat', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="surat-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/surat/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Surat */

$this->title = 'Sunting Surat';
$this->params['breadcrumbs'][] = ['label' => 'Surat', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Sunting';
?>
<div class="surat-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/surat/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use app\components\Helper;
use app\widgets\Label;

/* @var $this yii\web\View */
/* @var $model app\models\Surat */

$this->title = $model->ringkasan;
$this->params['breadcrumbs'][] = ['label' => 'Surat', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary surat-view">
    <div class="box-header with-border">
        <h1 class="box-title">Detail Surat <?= Html::encode($this->title) ?></h1>
    </div>
    <div class="box-body">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nomor',
            'tanggal',
            [
                'attribute' => 'id_surat_jenis',
                'value' => $model->suratJenis->nama,
            ],
            [
                'attribute' => 'id_surat_sifat',
                'value' => $model->suratSifat->nama,
            ],
            [
                'attribute' => 'id_jabatan_penandatangan',
                'value' => $model->jabatanPenandatangan->nama,
            ],
            'ringkasan',
            [
                'attribute' => 'username_pengaju',
                'value' => $model->jabatanPengaju !== null ? $model->jabatanPengaju->nama : null,
            ],
            [
                'attribute' => 'username_pembuat',
                'value' => $model->jabatanPembuat !== null ? $model->jabatanPembuat->nama : null,
            ],
            [
                'attribute' => 'id_surat_status',
                'format' => 'raw',
                'value' => function($data) {
                    return Label::widget([
                        'text' => $data->suratStatus->nama,
                        'context' => 'primary',
                    ]);
                }
            ]
        ],
    ]) ?>

    </div>
    <div class="box-footer with-border">
        <p>
            <?= Html::a('<i class="fa fa-pencil"></i> Sunting', ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-flat']) ?>
            <?= Html::a('<i class="fa fa-arrow-left"></i> Kembali', ['index', 'id' => $model->id], ['class' => 'btn btn-warning btn-flat']) ?>
        </p>
    </div>

</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">
            <i class="fa fa-print"></i> Pratinjau Surat : <?= Label::widget(['text' => 'Metode', 'context' => 'info']) ?>
        </h3>
    </div>
    <div class="panel-body">
        <iframe width="100%" height="500px" frameborder="0" src="<?= Url::to(['surat/pdf', 'id' => $model->id]) ?>">
        </iframe>
    </div>
</div>